name: Bug report
description: Report a problem with Cirq or the project.
labels: 'kind/bug-report'
body:
  - type: textarea
    attributes:
      label: Describe the issue
      description: Please explain in a clear and concise way what the issue is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How can the issue be reproduced?
      description: >-
        Explain in a step-by-step fashion what someone else would need to
        do in order to reproduce the issue. If possible, include literal
        examples of commands or code using [Markdown fenced code
        blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
        For long output, paste the text into [collapsed
        sections](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections)
        or attach text files.
    validations:
      required: false

  - type: input
    attributes:
      label: What version of Cirq are you using?
      description: >-
        You can find out the version of Cirq you are running by using Python
        to print the value of `cirq.__version__`. You can do this by running
        the command `python -c 'import cirq; print(cirq.__version__)'` in your
        Python environment. Please copy-paste the output in the field below.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: In what environment are you using Cirq?
      description: >-
        How are you running Cirq?
      options:
        - Google Colab
        - Python interpreter/REPL in Linux
        - Python interpreter/REPL in MacOS
        - Python interpreter/REPL in Windows
        - Jupyter notebook on Linux system
        - Jupyter notebook on MacOS system
        - Jupyter notebook on Windows system
    validations:
      required: false
