name: Debug remote CI

on:
  workflow_dispatch:
    inputs:
      what-to-debug:
        description: What to debug
        type: choice
        default: pytest
        options:
          - pytest
          - coverage
          - windows
          - macos
      py-version:
        description: Python version
        type: choice
        default: 3.12
        options:
          - 3.10
          - 3.11
          - 3.12
      os:
        description: OS
        type: choice
        default: ubuntu-20.04
        options:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-15
          - macos-14
          - macos-13
          - windows-2025
          - windows-2022
          - windows-2019

jobs:
  config:
    name: Configure this run
    runs-on: ${{github.event.inputs.os}}
    outputs:
      arch: ${{steps.determine.outputs.arch}}
    steps:
      - name: Determine architecture
        id: determine
        run: |
          case "${{github.event.inputs.os}}" in
            macos*)
              echo "arch=arm64" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "arch=x64" >> "$GITHUB_OUTPUT"
              ;;
          esac

  pytest:
    name: Run pytest on ${{github.event.inputs.os}} with Python ${{github.event.inputs.py-version}}
    needs: config
    runs-on: ${{github.event.inputs.os}}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{github.event.inputs.py-version}}
          architecture: ${{needs.config.outputs.arch}}
          cache: pip



      # - name: Set up caching of dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.pythonLocation }}
      #     key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt', 'dev_tools/requirements/**/*.txt') }}

      # - name: Install requirements
      #   run: |
      #     pip install wheel
      #     pip install --upgrade --upgrade-strategy eager -r dev_tools/requirements/dev.env.txt

      # - name: Run Quil dependencies
      #   run: docker compose -f cirq-rigetti/docker-compose.test.yaml up -d

      # - name: Pytest check
      #   run: check/pytest -n auto --durations=20 --ignore=cirq-core/cirq/contrib --rigetti-integration

      # - name: Stop Quil dependencies
      #   run: docker compose -f cirq-rigetti/docker-compose.test.yaml down
